project:
  type: website
  output-dir: docs

website:
  title: "Everyday ggplot2 extension: sublayer modularity 🫖"
  reader-mode: true
  repo-url: https://github.com/teunbrand/ggplot-extension-club
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: closereads-chunk-reveal.qmd
        text: Discuss
      - href: ggplot2-sublayer-modularity.qmd
        text: Discuss

    tools:
      - icon: github
        href: https://github.com/teunbrand/ggplot-extension-club
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Gina Reynolds"

format:
  html:
    theme: theme.scss
    toc: true

editor: source
