project:
  type: website
  output-dir: docs

website:
  title: "Everyday ggplot2 closereads 🫖"
  reader-mode: true
  repo-url: https://github.com/EvaMaeRey/crispy-octo-train
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: closereads-chunk-reveal.qmd
        text: First closeread
      - href: ggplot2-sublayer-modularity.qmd
        text: sublayer modularity
      - href: ggprefixes.qmd
        text: Extension Gallery Functions

    tools:
      - icon: github
        href: https://github.com/EvaMaeRey/crispy-octo-train
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Gina Reynolds"

format:
  html:
    theme: theme.scss
    toc: true

editor: source
