---
title: My First Closeread
format: closeread-html
---

Graphical poems with ggplot2.


```{r,include=F}
library(tidyverse)
cars <- tibble(cars)
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```


Closeread enables scrollytelling.

ggplot2 allows you build up your plot bit by bit - to write 'graphical poems' (Wickham 2010).  It is easy to gain insights simply by defining what aes


Here is a graphical poem!

```{r walkthrough, include = T}
ggplot(data = cars) + # The first declaration you typically make is the dataframe to plot
  aes(x = speed, y = dist) + # The second declaration is what visual channels should represent which variables (here x and y position are used to represent speed and distance)
  geom_point() + # Then you'll specify the mark (point here) that will take on the aesthetics (x or y position here, but color, size, shape are other examples)
  geom_smooth() # Finally we might be interested in making some predictions; what is the expected value (mean) of y given some x (here stopping distance given some speed upon breaking) 
```

But let's read it 'aloud' now...

```{r, echo = F}
cr_last_plot_construction <- ':::{focus-on="cr-.PLOTXXX"}\n.COMMENT, using `.CODE`\n:::\n\n:::{#cr-.PLOTXXX}\n```{r .PLOTXXX}\n.LEADING\n  .CODE\n```\n:::\n'  
```


```{r, echo = T}
knitr::knit_code$get("walkthrough") |>
  tibble(code_raw = _) |>
  mutate(comment = str_extract(code_raw, "#.+$")) |>
  mutate(comment = str_remove(comment, "#")) |>
  mutate(code = str_remove(code_raw, "\\+ #.+$|#.+$")) |>
  mutate(index = row_number()) |>
  mutate(plot_name = paste("walkthrough", sep = "-", index)) |>
  mutate(explosion = cr_last_plot_construction) |>
  mutate(explosion = str_replace_all(explosion, ".PLOTXXX", plot_name)) |>
  mutate(explosion = str_replace(explosion, ".COMMENT", comment)) |>
  mutate(explosion = str_replace_all(explosion, ".CODE", code)) |>
  mutate(explosion = str_replace(explosion, ".LEADING", ifelse(index == 1, "", "last_plot() +"))) |>
  pull(explosion) -> 
to_closeread

to_closeread
```

:::{.cr-section}

`r paste(knitr::knit(text = to_closeread, quiet = F), collapse = "\n\n")`

:::




